app/admin/routes.py
from flask import render_template, request, url_for, redirect, flash, Blueprint
from flask_login import login_required
from app import db
from app.main.utils import perfil_admin
from app.admin.utils import get_unidade_brief, get_turma_brief, get_equipe_brief, get_unidade_selected, editUnidade, get_turma_selected, get_equipe_selected, create_unidade, create_turma, create_equipe, createTurma
from app.admin.forms import RegistroUnidade, RegistroTurma
from app.models import Turma, Unidade, Endereco, Coordenador, Instrumento


admin = Blueprint('admin', __name__)



@admin.route("/admin", methods=['GET', 'POST'])
@login_required
def admin_home():  
    unidades = get_unidade_brief()
    turmas = get_turma_brief()
    equipes = get_equipe_brief() 
    form_create_und, path_u = create_unidade()
    form_perfil, data_nasc, image_file = perfil_admin()
    form_create_turma, path_t = create_turma()
    form_create_equipe, path_e= create_equipe()    
    return render_template("admin.html", formPerfil=form_perfil, dataNasc=data_nasc, image_file=image_file, formCreateUnd=form_create_und, formCreateTurma=form_create_turma, formCreateEquipe=form_create_equipe, unidades = unidades, turmas = turmas, equipes = equipes, pane_u = path_u, pane_t = path_t, pane_e = path_e)



@admin.route("/admin/<path>", methods=['GET', 'POST'])
@login_required
def admin_path(path):   
    unidades = get_unidade_brief()
    turmas = get_turma_brief()
    equipes = get_equipe_brief() 
    form_create_und, pane = create_unidade()
    form_create_equipe, pane = create_equipe() 
    form_perfil, data_nasc, image_file = perfil_admin()
    form_create_turma, pane =  create_turma()
    return render_template("admin.html", formPerfil=form_perfil, dataNasc=data_nasc, image_file=image_file, formCreateUnd=form_create_und, formCreateTurma=form_create_turma, formCreateEquipe=form_create_equipe, unidades = unidades, turmas = turmas, equipes = equipes, pane = path)



@admin.route("/unidade/<id>/delete", methods=['POST'])
@login_required
def delete_unidade(id):  
    unidade = Unidade.query.get_or_404(id)
    db.session.delete(unidade)
    db.session.commit()
    flash('A unidade foi removida!', 'success')
    return redirect(url_for('admin.admin_path', path='unidade'))



@admin.route("/turma/<id>/delete", methods=['POST'])
@login_required
def delete_turma(id):  
    turma = Turma.query.get_or_404(id)
    db.session.delete(turma)
    db.session.commit()
    flash('A turma foi removida!', 'success')
    return redirect(url_for('admin.admin_path', path='turma'))



@admin.route("/panel", methods=['GET'])
@login_required
def panel_select():         
    if request.args['pane'] == 'unidade':        
        panel = get_unidade_selected(request.args['id'])
    elif request.args['pane'] == 'turma':        
        panel = get_turma_selected(request.args['id'])
    elif request.args['pane'] == 'equipe':        
        panel = get_equipe_selected(request.args['id'])
    else:
        return redirect(url_for('admin.admin_home'))
    return panel



@admin.route("/unidade/<int:id>", methods=['GET', 'POST'])
def update_unidade(id):
    form = RegistroUnidade()
    form.gestor.choices = [(g.id, g.nome) for g in Coordenador.query.all()]
    if request.method == "POST" and request.form['type'] == 'formEditUnd':    
        if form.validate_on_submit():          
            editUnidade(form, id)            
            flash('Unidade atualizada com sucesso!', 'success')
            return redirect(url_for('admin.admin_path', path='unidade'))
        else:
            flash('Não foi possível atualizar os dados. Verifique as informações e tente novamente', 'danger')
    elif request.method == "GET":
        unidade = Unidade.query.filter_by(id = id).first()
        endereco = Endereco.query.filter_by(unidade_id = unidade.id).first()
        form.id.data = unidade.id  
        form.nome.data = unidade.nome
        form.endereco.data = endereco.rua
        form.bairro.data = endereco.bairro
        form.cidade.data = endereco.cidade
        form.cep.data = endereco.cep
        form.telefone.data = unidade.telefone
        form.email.data = unidade.email
        form.gestor.data = int(unidade.gestor)
          
    unidades = get_unidade_brief() 
    return render_template("admin.html", formEditUnd = form, unidades=unidades, pane = 'unidade')



@admin.route("/turma/<int:id>", methods=['GET', 'POST'])
def update_turma(id):
    form = RegistroTurma()
    form.unidade.choices = [(g.id, g.nome) for g in Unidade.query.all()]
    form.instrumento.choices = [(g.id, g.nome) for g in Instrumento.query.all()]
    form.nome_coordenador.choices = [(g.id, g.nome) for g in Coordenador.query.all()]
    path = 'turma'
    if request.method == "POST" and request.form['type'] == 'formCreateTurma':       
        if form.validate_on_submit():            
            createTurma(form)                       
            flash('Turma atualizada com sucesso!', 'success')  
            return redirect(url_for('admin.admin_path', path=path))
        else:
            flash('Não foi possível atualizar os dados. Verifique as informações e tente novamente', 'danger')
    elif request.method == "GET":
        turma = Turma.query.filter_by(id = id).first()
        form.id.data = turma.id  
        form.nome.data = turma.nome
        form.unidade.data = int(turma.unidade_id)
        form.instrumento.data = int(turma.instrumento_id)        
        form.dia_semana.data = int(turma.diaSemana)
        form.horario.data = turma.horario
        form.nome_coordenador.data = int(turma.coordenador_id)
          
    turmas = get_turma_brief() 
    return render_template("admin.html", formEditTurma = form, turmas=turmas, pane = path)

app/templates/includes/add_turma.html
<div class="hidden hide-container" id="telaCadastroCurso">
    <div class="bg-container justify-content-center" >
        <div class="background-dark">
        </div>
        <div class="tela-add-curso tela-add-item border rounded shadow  p-4 bg-white">
            <form action="" method="POST">
              {% if formCreateTurma %}
                {{ formCreateTurma.hidden_tag() }}
                <div class="text-center mb-3">
                    <span class="h5 text-info font-weight-bold">Cadastro de Turma</span>
                    <button  class="close btn-add-curso " data-element="#telaCadastroCurso" data-dismiss="tela-add-curso" aria-label="Fechar">
                        <span class="btn-add-curso m-3" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="form-group">
                    <label for="nomeCurso">Nome do Turma</label>
                    {% if formCreateTurma.nome.errors %}
                    {{ formCreateTurma.nome(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.nome.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.nome(class='form-control', placeholder='Nome da Turma')}} 
                  {% endif %} 
                </div>
                <div class="form-group">
                    <label for="nomeUnidade">Unidade de Ensino</label>
                    {% if formCreateTurma.unidade.errors %}
                    {{ formCreateTurma.unidade(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.unidade.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.unidade(class='form-control', placeholder='Nome da Unidade')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="instrumentoCurso">Instrumento</label>
                    {% if formCreateTurma.instrumento.errors %}
                    {{ formCreateTurma.instrumento(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.instrumento.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.instrumento(class='form-control', placeholder='Nome do Instrumento')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="diaDaSemana">Dia da Semana</label>
                    {% if formCreateTurma.dia_semana.errors %}
                    {{ formCreateTurma.dia_semana(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.dia_semana.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.dia_semana(class='form-control')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="horario">Horário: </label>
                    {% if formCreateTurma.horario.errors %}
                    {{ formCreateTurma.horario(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.horario.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.horario(class='form-control')}} 
                  {% endif %}                         
                </div>
                <div class="form-group">
                    <label for="inputCoordenador">Coordenador do Curso</label>
                    {% if formCreateTurma.nome_coordenador.errors %}
                    {{ formCreateTurma.nome_coordenador(class='form-control is-invalid')}}
                      {% for error in formCreateTurma.nome_coordenador.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formCreateTurma.nome_coordenador(class='form-control')}} 
                  {% endif %} 
                </div>
                <div class="d-none">
                    {{ formCreateTurma.type( value='formCreateTurma')}} 
                </div>
                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-primary ">Salvar</button>
                    <button type="button" class="btn btn-secondary ml-4  btn-add-curso" data-element="#telaCadastroCurso">Cancelar</button>
                </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>

app/templates/includes/edit_turma.html
{% if  formEditTurma %}
    <div class="bg-container justify-content-center" >
            <div class="background-dark">
            </div>
            <div class="tela-edit-escola tela-add-item border rounded shadow p-4 bg-white" >
            
            <form action="" method="POST">
                {{ formEditTurma.hidden_tag() }}
                <div class="text-center mb-3">
                    <span class="h5 text-info font-weight-bold">Cadastro de Turma</span>
                    <a href="{{url_for('admin.admin_path', path='turma' )}}" class="close ">
                        <span  class="btn-edit-escola toogle-hide m-3" aria-hidden="true">&times;</span>
                        </a>
                </div>
                <div class="form-group">
                    <label for="nomeCurso">Nome do Turma</label>
                    {% if formEditTurma.nome.errors %}
                    {{ formEditTurma.nome(class='form-control is-invalid')}}
                      {% for error in formEditTurma.nome.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.nome(class='form-control', placeholder='Nome da Turma')}} 
                  {% endif %} 
                </div>
                <div class="form-group">
                    <label for="nomeUnidade">Unidade de Ensino</label>
                    {% if formEditTurma.unidade.errors %}
                    {{ formEditTurma.unidade(class='form-control is-invalid')}}
                      {% for error in formEditTurma.unidade.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.unidade(class='form-control', placeholder='Nome da Unidade')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="instrumentoCurso">Instrumento</label>
                    {% if formEditTurma.instrumento.errors %}
                    {{ formEditTurma.instrumento(class='form-control is-invalid')}}
                      {% for error in formEditTurma.instrumento.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.instrumento(class='form-control', placeholder='Nome do Instrumento')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="diaDaSemana">Dia da Semana</label>
                    {% if formEditTurma.dia_semana.errors %}
                    {{ formEditTurma.dia_semana(class='form-control is-invalid')}}
                      {% for error in formEditTurma.dia_semana.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.dia_semana(class='form-control')}} 
                  {% endif %}
                </div>
                <div class="form-group">
                    <label for="horario">Horário: </label>
                    {% if formEditTurma.horario.errors %}
                    {{ formEditTurma.horario(class='form-control is-invalid')}}
                      {% for error in formEditTurma.horario.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.horario(class='form-control')}} 
                  {% endif %}                         
                </div>
                <div class="form-group">
                    <label for="inputCoordenador">Coordenador do Curso</label>
                    {% if formEditTurma.nome_coordenador.errors %}
                    {{ formEditTurma.nome_coordenador(class='form-control is-invalid')}}
                      {% for error in formEditTurma.nome_coordenador.errors %}
                        <div class="invalid-feedback">
                          <span>{{error}}</span>
                        </div>
                      {% endfor %}
                  {% else %} 
                    {{ formEditTurma.nome_coordenador(class='form-control')}} 
                  {% endif %} 
                </div>
                <div class="d-none">
                    {{ formEditTurma.type( value='formEditTurma')}} 
                </div>
                <div class="d-none">
                    {{ formEditTurma.id()}} 
                </div>
                <div class="text-center mt-3 row justify-content-center">
                    <div class="col-10">
                        {{ formEditTurma.submit(class='btn btn-primary text-white submit_update_unidade')}}
                        <a href="{{url_for('admin.admin_path', path='turma' )}}" class="btn btn-secondary ml-4 " >Cancelar</a>
                    </div>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target=".deleteModal">Remover</button>
                </div>
            </form>
                    
        </div>
        
    </div>
</div>

<!-- Modal -->
<div class="modal fade deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Apagar Turma?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
    <form action="{{url_for('admin.delete_turma', id=formEditTurma.id.data )}}" method="POST">
        <input class="btn btn-danger" type="submit" value="Apagar">
    </form>
</div>
</div>
</div>
{% endif %}

app/templates/includes/edit_unidade.html
{% if  formEditUnd %}
    <div class="bg-container justify-content-center" >
            <div class="background-dark">
            </div>
            <div class="tela-edit-escola tela-add-item border rounded shadow p-4 bg-white" >
                
                <form action="" method="POST">                    
                    {{ formEditUnd.hidden_tag() }}
                    <div class="text-center mb-3">
                        <span class="h5 text-info font-weight-bold">Cadastro de Escola</span>
                        <a href="{{url_for('admin_path', path='unidade')}}" class="close ">
                            <span  class="btn-edit-escola toogle-hide m-3" aria-hidden="true">&times;</span>
                            </a>
                    </div>
                    <div class="form-group">
                        <label for="nomeEscola">Nome da Escola</label>
                        {% if formEditUnd.nome.errors %}
                        {{ formEditUnd.nome(class='form-control is-invalid')}}
                          {% for error in formEditUnd.nome.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.nome(class='form-control', placeholder='nome')}} 
                      {% endif %} 
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Endereço</label>
                        {% if formEditUnd.endereco.errors %}
                        {{ formEditUnd.endereco(class='form-control is-invalid')}}
                          {% for error in formEditUnd.endereco.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.endereco(class='form-control', placeholder="Rua XV de Novembro, nº 0")}} 
                      {% endif %} 
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                        <label for="inputBairro">Bairro</label>
                        {% if formEditUnd.bairro.errors %}
                        {{ formEditUnd.bairro(class='form-control is-invalid')}}
                          {% for error in formEditUnd.bairro.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.bairro(class='form-control', placeholder="bairro")}} 
                      {% endif %}
                        </div>
                        <div class="form-group col-md-5">
                            <label for="inputTelefone">Cidade</label>
                            {% if formEditUnd.cidade.errors %}
                        {{ formEditUnd.cidade(class='form-control is-invalid')}}
                          {% for error in formEditUnd.cidade.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.cidade(class='form-control', placeholder="cidade")}} 
                      {% endif %}
                        </div>
                        <div class="form-group col-md-3">
                        <label for="inputCEP">CEP</label>
                        {% if formEditUnd.cep.errors %}
                        {{ formEditUnd.cep(class='form-control is-invalid')}}
                          {% for error in formEditUnd.cep.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.cep(class='form-control', placeholder="CEP")}} 
                      {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nomeGestor">Responsável</label>
                        {% if formEditUnd.gestor.errors %}
                        {{ formEditUnd.gestor(class='form-control is-invalid')}}
                          {% for error in formEditUnd.gestor.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.gestor(class='form-control')}} 
                      {% endif %} 
                    </div>
                    <div class="form-row">                        
                        <div class="form-group col-md-6">
                            <label for="inputTelefone">Telefone</label>
                            {% if formEditUnd.telefone.errors %}
                        {{ formEditUnd.telefone(class='form-control is-invalid')}}
                          {% for error in formEditUnd.telefone.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.telefone(class='form-control', placeholder="telefone")}} 
                      {% endif %}
                        </div>
                        <div class="form-group col-md-6">
                        <label for="inputEmail">Email</label>
                        {% if formEditUnd.email.errors %}
                        {{ formEditUnd.email(class='form-control is-invalid')}}
                          {% for error in formEditUnd.email.errors %}
                            <div class="invalid-feedback">
                              <span>{{error}}</span>
                            </div>
                          {% endfor %}
                      {% else %} 
                        {{ formEditUnd.email(class='form-control', placeholder="email")}} 
                      {% endif %}
                        </div>
                    </div>
                    <div class="d-none">
                        {{ formEditUnd.type( value='formEditUnd')}} 
                    </div>
                    <div class="d-none">
                        {{ formEditUnd.id()}} 
                    </div>
                    <div class="text-center mt-3 row justify-content-center">
                        <div class="col-10">
                            {{ formEditUnd.submit(class='btn btn-primary text-white submit_update_unidade')}}
                            <a href="{{url_for('admin.admin_path', path='unidade')}}" class="btn btn-secondary ml-4 " >Cancelar</a>
                        </div>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target=".deleteModal">Remover</button>
                    </div>
                </form>
                    
                </div>
                
            </div>
    </div>

 <!-- Modal -->
 <div class="modal fade deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Apagar Unidade?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            <form action="{{url_for('admin.delete_unidade', id=formEditUnd.id.data )}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Apagar">
            </form>
        </div>
    </div>
</div>
{% endif %}

app/templates/includes/equipe_select.html
<div class="wrapper wrapper-dados-item wrapper-dados-equipe border my-5 pr-4 pl-4  rounded shadow hidden hide-toggle-tab mx-auto widht-page" id="dataInfoEquipe">
    <div class="container-fluid py-3 mb-2">
        <form>
            <div class="row">
                <div class="col-11 text-center mb-3">
                    <span class="h5 text-info font-weight-bold ">Cadastro do Colaborador</span>
                </div>
                <div class="col ml-auto">
                    <a href="" class="mb-auto btn-edit-equipe toogle-hide ml-1" data-element="#telaEditEquipe"><i class='bx bx-edit text-info'  style="font-size: 1.75rem"></i></a>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-8 mb-3">
                    <label for="nomeCurso">Nome do Colaborador</label>
                <input value="" type="text" class="form-control bg-white" id="form-nomeEquipe" placeholder="Nome" disabled>
                </div>
                <div class="form-group col-md-4 mb-3">
                    <label for="dataNascimento">Data Nascimento</label>
                    <input value="" id="form-dataNascimento" type="text" class="form-control ml-2 p-1 rounded  bg-white" placeholder="dd/mm/aa"  disabled>
                </div>
            </div>
            <div class="form-group">
                <label for="enderecoEquipe">Endereço</label>
                <input value="" type="text" class="form-control bg-white" id="form-enderecoEquipe" placeholder="Rua XV de Novembro, nº 0" disabled>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="email">Email</label>
                <input value="" type="email" class="form-control bg-white" id="form-emailEquipe" placeholder="email" disabled>
                </div>                                   
                <div class="form-group col-md-6">
                    <label for="telefone">Telefone</label>
                <input value="" type="text" class="form-control bg-white" id="form-telefoneEquipe" placeholder="telefone" disabled>
                </div>
            </div>
            <hr>
            <!--
            <div class="form-row">
                <div class="form-group col-md-6 text-center">
                    <label for="turmaEquipe">Turmas</label>
                    <ul class="list-group text-center">
                        <li class="list-group-item">Violino Básico I - Belo Hosizonte</li>
                        <li class="list-group-item">Violão Básico I - Betim</li>
                        <li class="list-group-item">Saxofone Básico II - Contagem</li>
                        </ul>
                </div>
                <div class="form-group col-md-6 text-center">
                    <label for="instrumentosEquipe">Instrumentos</label>
                    <ul class="list-group">
                        <li class="list-group-item">Violino</li>
                        <li class="list-group-item">Violão</li>
                        <li class="list-group-item">Saxofone</li>
                        <li class="list-group-item">Piano</li>
                        
                        </ul>
                </div>                
            </div>
            -->
        </form>
    </div>
</div>

app/templates/includes/equipes.html
    <div class="container-fluid">
        <div class="row mt-1">
            <div class="ml-auto mr-3">                                
                <a class="btn-add-equipe toogle-hide" id="addEquipeBtn" href="#" data-element="#telaCadastroEquipe"><i class="fa fa-2x fa-plus-circle text-info m-2" aria-hidden="true"></i></a>                   
            </div>
        </div>
        <div class="row mt-2">
            <table class="table table-hover text-center">
                <thead class="bg-gray">
                <tr>                            
                    <th scope="col">Nome</th>                                    
                    <th scope="col">Função</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Editar</th>
                </tr>
                </thead>
                <tbody>
                    {% if equipes %}
                {% for equipe in  equipes %}
                  <tr>                            
                    <td>{{ equipe['nome']}}</td>
                    <td>{{ equipe['funcao']}}</td>
                    <td>{{ equipe['telefone']}}</td>
                    <td>{{ equipe['email']}}</td>
                    <td> 
                        <a href="#" class="open-info-equipe toogle-hide ml-auto" data-element="#dataInfoEquipe" data-pane="equipe" data-id= "{{equipe['id']}}"><i class='bx bx-file-find text-info mt-auto' style="font-size: 1.75rem"></i></a>                                 
                    </td>
                </tr>
                {% endfor %} 
                {% endif %}                                         
                </tbody>
            </table>
        </div>                
    </div>

</div>
</div>
</div>