app/acervo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,  SubmitField, DateField, TextAreaField, SelectField
from wtforms.validators import InputRequired, Length, ValidationError, Optional
from app.models import  Tipoinstrumento



class RegistroTipoInstrumento(FlaskForm):
    instrumento = StringField('Marca',
                              validators=[InputRequired(), Length(min=2,max=50)])
    codigo = StringField('Marca',
                              validators=[InputRequired(), Length(min=2,max=4)])
    type = StringField('RegistroTipoInstrumento')
    submit = SubmitField('Salvar')
    
    def validate_instrumento(self, instrumento):        
        if Tipoinstrumento.query.filter_by(nome = instrumento.data).first():
            raise ValidationError('Este instrumento já existe. Escolha um nome de instrumento diferente')
        
    def validate_codigo(self, codigo):        
        if Tipoinstrumento.query.filter_by(codigo = codigo.data).first():
            raise ValidationError('Este codigo já existe. Escolha um codigo diferente')
   
   
   

class RegistroInstrumento(FlaskForm):
    instrumento = SelectField('Instrumento', 
                                   coerce=int, validators=[])
    marca = StringField('Marca',
                              validators=[InputRequired(), Length(min=2,max=50)])
    estado_instrumento = SelectField('Turma', 
                                   choices=[(1, 'Novo'),(2, 'Muito bom'),(3, 'Bom'),(4, 'Regular'),(5, 'Ruim')], validators=[Optional()])
    unidade = SelectField('Unidade', 
                                   coerce=int, validators=[])
    data_aquisicao = DateField('Data de Aquisição', format="%Y-%m-%d", validators=[Optional()])
    anotacoes = TextAreaField('Anotações',
                              validators=[Length(max=300)])
    type = StringField('RegistroInstrumento')
    submit = SubmitField('Salvar')

app/aluno/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, DateField, TextAreaField, SelectField
from wtforms.validators import InputRequired, Length, Email, ValidationError, Optional
from app.models import Aluno


class RegistroAluno(FlaskForm):
    imagem = FileField("Imagem", 
                      validators=[FileAllowed(['jpg', 'png'])])
    nome = StringField('Nome',
                              validators=[InputRequired(), Length(min=2,max=20)])
    turma = SelectField('Turma', 
                                   coerce=int, validators=[Optional()])
    email = StringField('Email',
                        validators=[InputRequired(), Email()])
    telefone = StringField('Telefone',
                              validators=[])
    data_nasc = DateField('Data de Nascimento', format="%Y-%m-%d", validators=[])
    data_admissao = DateField('Data de Admissão', format="%Y-%m-%d", validators=[Optional()])
    data_desligamento = DateField('Data de Desligamento', format="%Y-%m-%d", validators=[])
    nome_responsavel = StringField('Nome',
                              validators=[Length(min=2,max=20)])
    email_responsavel = StringField('Email',
                        validators=[Email()])
    telefone_responsavel = StringField('Telefone',
                              validators=[])
    anotacoes = TextAreaField('Anotações',
                              validators=[Length(max=400)])
    endereco = StringField('Endereço',
                              validators=[Length(min=2,max=100)])
    bairro = StringField('Bairro',
                              validators=[Length(min=2,max=20)])
    cidade = StringField('Cidade',
                              validators=[Length(min=2,max=20)])
    cep = StringField('CEP',
                              validators=[])
        
    type = StringField('RegistroAluno')
    submit = SubmitField('Salvar')
    
    def validate_email(self, email):        
        if Aluno.query.filter_by(email = email.data).first():
            raise ValidationError('Este email já existe. Escolha um email diferente para o colaborador')

app/acervo/routes.py
from flask import Blueprint, render_template
from flask_login import login_required
from app.acervo.utils import get_instrumento_brief, create_tipo_instrumento, create_instrumento
from app.main.utils import perfil_admin

acervo = Blueprint('acervo', __name__)


@acervo.route("/acervo", methods=['GET', 'POST'])
@login_required
def acervo_home():
    instrumentos = get_instrumento_brief()  
    formCreateTipoInstrumento = create_tipo_instrumento()
    formCreateInstrumento = create_instrumento()
    formPerfil, dataNasc, image_file = perfil_admin()
    return render_template("acervo.html", formPerfil=formPerfil, dataNasc=dataNasc, image_file=image_file, formCreateTipoInstrumento=formCreateTipoInstrumento, formCreateInstrumento=formCreateInstrumento, instrumentos=instrumentos)

app/aluno/routes.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from app.aluno.utils import create_aluno, get_alunos_brief, get_alunos_select
from app.main.utils import perfil_admin
from app.models import Aluno

aluno = Blueprint('aluno', __name__)


@aluno.route("/alunos", methods=['GET', 'POST'])
@login_required
def alunos():
    form_create_aluno = create_aluno()
    alunos = get_alunos_brief()  
    form_perfil, data_nasc, image_file = perfil_admin()
    return render_template("alunos.html", formPerfil=form_perfil, dataNasc=data_nasc, image_file=image_file, alunos = alunos, formCreateAluno = form_create_aluno)


@aluno.route("/alunos/<int:id>", methods=['GET', 'POST'])
@login_required
def alunos_select(id):
    aluno = get_alunos_select(id) 
    return aluno



@aluno.route("/aluno/cadastro/<int:id>", methods=['GET', 'POST'])
@login_required
def alunos_edit(id):
    form_edit_aluno = create_aluno()
    alunos = get_alunos_brief()
    aluno = get_alunos_select(id)   
    form_perfil, data_nasc, image_file = perfil_admin()
    if request.method == "GET":
        aluno = Aluno.query.get(id)
        form_edit_aluno.nome.data = aluno.nome
        form_edit_aluno.email.data = aluno.email
        form_edit_aluno.telefone.data = aluno.telefone
        form_edit_aluno.data_nasc.data = aluno.dataNasc
        form_edit_aluno.data_admissao.data = aluno.dataAdmissao
        form_edit_aluno.data_desligamento.data = aluno.dataDesligamento
        form_edit_aluno.nome_responsavel.data = aluno.nomeResponsavel
        form_edit_aluno.email_responsavel.data = aluno.emailResponsavel
        form_edit_aluno.telefone_responsavel.data = aluno.telefoneResponsavel
        form_edit_aluno.anotacoes.data = aluno.anotacoesAluno
    return render_template("alunos.html", formPerfil=form_perfil, dataNasc=data_nasc, image_file=image_file, alunos = alunos, formEditAluno = form_edit_aluno, aluno = aluno)

app/user/routes.py
from flask import Blueprint, render_template
from flask import render_template, request, url_for, redirect, flash
from flask_login import login_user, current_user, logout_user
from app import db, bcrypt
from app.user.utils import createUser, send_request_email
from app.user.forms import RegistrationForm, LoginForm, RequestPassword, ResetPassword
from app.models import Admin

user = Blueprint('user', __name__)



@user.route("/register", methods=['GET', 'POST'] )
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.logout'))
    form = RegistrationForm()
    if request.method == "POST":   
        if  form.validate_on_submit():
            createUser(form)
            flash('Sua conta foi criada com sucesso!', 'success')
            return redirect(url_for('user.login'))
        else:
            flash('Não foi possível criar sua conta. Confirme seus dados e tente novamente', 'danger')
    return render_template("register.html", title= 'Register', form=form)




@user.route("/", methods=['GET', 'POST'] )
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.logout'))
    form = LoginForm()
    if request.method == "POST":        
        if form.validate_on_submit():
            usuario = Admin.query.filter_by(email=form.email.data).first()
            if usuario and bcrypt.check_password_hash(usuario.checksum, form.password.data):
                login_user(usuario, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
            else:
                flash('Não foi possível acessar sua conta. Confirme seus dados e tente novamente', 'danger')
    return render_template("login.html", title='Login', form=form)



@user.route("/logout", methods=['GET', 'POST'] )
def logout():
    logout_user()
    return redirect(url_for('user.login'))
    


@user.route("/reset_password", methods=["GET", "POST"])
def request_password():
    if current_user.is_authenticated:
        return redirect(url_for('user.logout'))
    form = RequestPassword()
    if form.validate_on_submit():
        user = Admin.query.filter_by(email = form.email.data).first()
        send_request_email(user)
        flash('Foi enviado um email com as instruções para recuperar sua senha', 'info')
        return redirect(url_for('user.login'))
    return render_template('request_password.html', title="Recuperar Senha", form=form)



@user.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('user.logout'))
    user = Admin.verify_reset_token(token)
    if not user:
        flash('O link para recuperar a senha expirou. Envie o link novamente', 'warning')
        return redirect(url_for('user.request_password'))
    form = ResetPassword()
    if form.validate_on_submit():
        hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.checksum = hash_password
        db.session.commit()
        flash('Sua senha foi atualizada com sucesso', 'success')
        return redirect(url_for('user.login'))
    return render_template('reset_password.html', title="Atualizar Senha", form=form)

app/templates/admin.html
{% extends "layout.html" %}

{% block title %}Administração{% endblock %}

{% block pageCurrent %}Administração{% endblock  %}

{% block body %}
{{pane}}
<!--Conteudo Principal de Cada Pagina-->
<div class="main mx-auto widht-page">
    <div class="wrapper wrapper-tab border p-4 rounded shadow bg-white">        
        <div>
            <!--NavTab para os dados das Escolas / Equipe / Alunos-->
            <div class="nav nav-tabs " id="nav-tab" role="tablist">
                <a {% if (not pane or pane == 'unidade') and (not pane_t and not pane_e)  %}
                      class="nav-item nav-link nav_link_table toogle-hide text-dark active"
                    {% else %}
                      class="nav-item nav-link nav_link_table toogle-hide text-dark"
                    {% endif %}                
                id="nav-escolas-tab" data-toggle="tab" href="#nav-escolas" role="tab" aria-controls="nav-escolas" aria-selected="false" data-element=".hide-toggle-tab">Unidades</a>
                <a {% if pane_t == "turma" or pane == 'turma' %}
                    class="nav-item nav-link nav_link_table toogle-hide text-dark active"
                  {% else %}
                    class="nav-item nav-link nav_link_table toogle-hide text-dark"
                  {% endif %}  
                class="nav-item nav-link nav_link_table toogle-hide text-dark " id="nav-cursos-tab" data-toggle="tab" href="#nav-cursos " role="tab" aria-controls="nav-cursos" aria-selected="false">Turmas</a>
                <a {% if pane_e == "equipe" or pane == 'equipe' %}
                      class="nav-item nav-link nav_link_table toogle-hide text-dark active"
                    {% else %}
                      class="nav-item nav-link nav_link_table toogle-hide text-dark"
                  {% endif %}  
                class="nav-item nav-link nav_link_table toogle-hide text-dark " id="nav-equipe-tab" data-toggle="tab" href="#nav-equipe" role="tab" aria-controls="nav-equipe" aria-selected="true">Equipe</a>             
            </div>
           
        </div>

        <div class="tab-content" id="nav-tabContent">

            <!--Painel referente aos dados das Unidades da Ensino-->
            {% if (not pane or pane == 'unidade') and (not pane_t and not pane_e)   %}
            <div class="tab-pane fade show active tela-wrapper-table" id="nav-escolas" role="tabpanel" aria-labelledby="nav-escolas-tab">
            {% else %}
            <div class="tab-pane fade tela-wrapper-table" id="nav-escolas" role="tabpanel" aria-labelledby="nav-escolas-tab">
            {% endif %} 
            {% include 'includes/unidades.html'%}
            </div>

            <!--Painel referente aos dados das Turmas da organização-->
            {% if pane_t == "turma" or pane == 'turma' %}
            <div class="tab-pane fade show active tela-wrapper-table" id="nav-cursos" role="tabpanel" aria-labelledby="nav-cursos-tab">
            {% else %}
            <div class="tab-pane fade tela-wrapper-table" id="nav-cursos" role="tabpanel" aria-labelledby="nav-cursos-tab">
            {% endif %} 
            {% include 'includes/turmas.html'%}

            <!--Painel referente aos dados da Equipe da organização-->
            {% if pane_e == "equipe" or pane == 'equipe' %}
            <div class="tab-pane fade show active tela-wrapper-table" id="nav-equipe" role="tabpanel" aria-labelledby="nav-equipe-tab">
            {% else %}
            <div class="tab-pane fade tela-wrapper-table" id="nav-equipe" role="tabpanel" aria-labelledby="nav-equipe-tab">
            {% endif %} 
            {% include 'includes/equipes.html'%}
        </div>
    </div>
</div>
    

<!--Tabela com os dados da escola selecionada-->
  {% include 'includes/unidade_select.html'%}        

<!--Tabela com os dados da turma selecionada-->
  {% include 'includes/turma_select.html'%}

<!--Tabela com os dados da Equipe selecionada-->
  {% include 'includes/equipe_select.html'%}

<br>


<!--Modal para adicional Escola-->
<div class="hidden hide-container" id="telaCadastroEscola"> 
  {% include 'includes/add_unidade.html'%}
</div>

<!--Modal para adicional Turma-->
{% include 'includes/add_turma.html'%}

<!--Modal para adicional Equipe-->
{% include 'includes/add_equipe.html'%}

<!--Modal para editar Escola-->
{% if pane == "unidade" %}
<div class="" >
  {% else %}
<div class="hidden hide-container">
  {% endif %}  
{% include 'includes/edit_unidade.html'%}
</div>

<!--Modal para editar Escola-->
{% if pane == "turma" %}
<div class="" >
  {% else %}
<div class="hidden hide-container">
  {% endif %}  
{% include 'includes/edit_turma.html'%}
</div>




{% endblock  %}

app/templates/alunos.html
{% extends "layout.html" %}

{% block title %}Alunos{% endblock %}

{% block pageCurrent %}Alunos{% endblock  %}

{% block body %}

<!--Conteudo Principal de Cada Pagina-->
<div class="main mx-auto widht-page">
    <div class="wrapper wrapper-tab border p-4 rounded shadow bg-white" style="overflow-x: auto;">

        <!--Painel referente aos dados dos Alunos-->        
        <div class="container-fluid" >
            <div class="row mt-1">
                <div class="text-muted">
                    <h5>Alunos Orquestra Escola Criarte</h5>
                </div>
                <div class="ml-auto mr-3">                                
                    <a class="btn-add-aluno toogle-hide" id="addAlunoBtn" href="#" data-element="#telaCadastroAluno"><i class="fa fa-2x fa-plus-circle text-info m-2" aria-hidden="true"></i></a>                   
                </div>
            </div>
            <div class="row mt-2 tela-wrapper-table">
                <table class="table table-hover tela-wrapper-table" id="table-alunos">
                    <thead class="bg-gray">
                        <tr>
                            <th scope="col"><span class="mr-3 ">Nome</span><a href="#" ><i class="fa fa-sort text-muted" aria-hidden="true"></i></a></th>
                            <th scope="col"><span class="mr-3 ">Unidade</span><a href="#"><i class="fa fa-sort text-muted" aria-hidden="true"></i></a></th>
                            <th scope="col"><span class="mr-3 ">Turma</span><a href="#"><i class="fa fa-sort text-muted mr-0" aria-hidden="true"></i></a></th>
                            <th scope="col"><span class="mr-3 ">Instrumento</span><a href="#"><i class="fa fa-sort text-muted" aria-hidden="true"></i></a></th>
                            <th scope="col"><span class="mr-3 ">Data Admissão</span><a href="#"><i class="fa fa-sort text-muted" aria-hidden="true"></i></a></th>                            
                            <th scope="col"><span class="mr-3 ">Info</span><a href="#"><i class="fa fa-sort text-muted" aria-hidden="true"></i></a></th>  
                        </tr>
                    </thead>
                    <tbody>
                        {% if alunos %}
                        {% for aluno in  alunos %}
                        <tr>
                            <td>{{ aluno['nome'] }}</td>
                            <td>{{ aluno['unidade'] }}</td>
                            <td>{{ aluno['turma'] }}</td>
                            <td>{{ aluno['instrumento'] }}</td>
                            <td>{{ aluno['data_admissao'] }}</td><td>
                              <a href="" class="open-info-aluno toogle-hide ml-auto"data-element="#dataInfoAluno" data-id="{{aluno['id']}}"><i class="bx bx-file-find text-info mt-auto" style="font-size: 1.75rem"></i></a>
                            </td>
                          </tr>
                      {% endfor %} 
                      {% endif %}                                   
                      </tbody>
                </table>
            </div>                
        </div>
        
    </div>
</div>   



<!--Tabela com os dados do Aluno selecionada-->
{% include "includes_alunos/aluno_select.html" %}

<br>


<!--Modal para adicional Aluno-->
{% include 'includes_alunos/add_aluno.html'%}


<!--Modal para adicional Aluno-->
{% include 'includes_alunos/edit_aluno.html'%}


{% endblock  %}

app/templates/dashboard.html
{% extends "layout.html" %}

{% block title %}Home{% endblock %}

{% block pageCurrent %}Dashboard{% endblock  %}

{% block body %}

<!--Conteudo Principal de Cada Pagina-->
<div class="main justify-content-center mx-auto widht-page" >
    <div class=" wrapper-tab mr-2 ml-2">   
        <div class="row mb-4 justify-content-between" style="height: 130px;">
            <div class="col  border p-2  mr-3  rounded shadow text-white" style="background-color: #4472C4;">
                <div class="row justify-content-between mr-1 ml-1">
                    <label  class="text-left  h6">Alunos</label>
                    <i class="fa fa-user" aria-hidden="true" style="font-size: 1.6rem"></i>
                </div>               
                <div class="text-center mt-3">
                    <span id="totalAlunosdash" class="h1  font-weight-bold">-</span>
                </div>
            </div>
            <div class="col  border p-2  mr-3  rounded shadow text-white" style="background-color: #4472C4;">
                <div class="row justify-content-between mr-1 ml-1">
                    <label class="text-left  h6">Média idade</label>
                    <i class="fa fa-child" aria-hidden="true" style="font-size: 1.6rem"></i>
                </div>               
                <div class="text-center mt-3">
                    <span id="mediaIdadedash" class="h1  font-weight-bold">-</span>
                </div>
            </div>
            <div class="col  border p-2  mr-3  rounded shadow text-white" style="background-color: #4472C4;">
                <div class="row justify-content-between mr-1 ml-1">
                    <label class="text-left  h6">Instrumentos</label>
                    <i class="fa fa-music" aria-hidden="true" style="font-size: 1.6rem"></i>
                </div>               
                <div class="text-center mt-3">
                    <span id="totalInstrdash" class="h1  font-weight-bold">-</span>
                </div>
            </div>
            <div class="col  border p-2  mr-3  rounded shadow text-white" style="background-color: #4472C4;">
                <div class="row justify-content-between mr-1 ml-1">
                    <label class="text-left  h6">Turmas</label>
                    <i class="fa fa-users" aria-hidden="true" style="font-size: 1.6rem"></i>
                </div>               
                <div class="text-center mt-3">
                    <span id="totalTurmasdash" class="h1  font-weight-bold">-</span>
                </div>
            </div>
            <div class="col  border p-2  rounded shadow text-white" style="background-color: #4472C4;">
                <div class="row justify-content-between mr-1 ml-1">
                    <label class="text-left  h6">Popular</label>
                    <i class="fa fa-line-chart" aria-hidden="true"  style="font-size: 1.6rem"></i>
                </div>               
                <div class="text-center mt-3">
                    <span id="popInstrdash" class="h1  font-weight-bold">-</span>
                </div>
            </div>
        </div>
    </div> 

    <div class=" wrapper  border p-4 rounded shadow bg-white justify-content-center">              
        <div class="row mb-5">
            <div class="col">
                <div class="mb-5 align-items-end">
                    <div class="">
                        <label class="text-secondary h5">Alunos por Turma</label>
                    </div>
                    <div style="">
                        <canvas class="" id="model05"></canvas>
                    </div>
                </div>
                <div class="col-md justify-content-center mb-5">
                    <div class="">
                        <label class="text-secondary h5">Matrículas Por Unidade</label>
                    </div>
                    <div style="max-height: 500px;">
                        <canvas id="model03"></canvas>
                    </div>
                </div>                
                
                <div class="col-md mb-5">
                    <div class="">
                        <label class="text-secondary h5 ">Idade dos Alunos</label>
                    </div>
                    <div style="max-height: 400px;">
                        <canvas class="" id="model06"></canvas>
                    </div>
                </div>
                
                <div class="col-md justify-content-center mb-5">
                    <div class="">
                        <label class="text-secondary h5">Acervo/Empréstimos Por Unidade</label>
                    </div>
                    <div style="max-height: 400px;">
                        <canvas id="model01"></canvas>
                    </div>
                    <div class="row">
                        <div class="ml-3">
                            <div class="mr-2">
                                <button class="btn" style="background-color: #4472C4; pointer-events: none;"></button>
                                <spam id="unidadeId0" style="font-size: smaller;">-</spam>
                            </div>
                        </div>
                        <div class="">
                            <div class="mr-2">
                                <button class="btn" style="background-color: #ED7D31;pointer-events: none;"></button>
                                <spam id="unidadeId1" style="font-size: smaller;">-</spam>
                            </div>
                        </div>              
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="mb-5">
                    <div class="">
                        <label class="text-secondary h5">Alunos Por Unidade</label>
                    </div>
                    <div style="">
                        <canvas class="mx-auto" id="model02" style="min-height: 170px;"></canvas>
                    </div>
                </div>
                <div class="col-md mb-5">
                    <div class="">
                        <label class="text-secondary h5">Popularidade Instrumentos por Unidade</label>
                    </div>
                    <div>
                        <canvas class="mx-auto" id="model04" style="min-height: 200px;"></canvas>
                    </div>               
                </div>
                <div class="col-md mb-5">
                    <div class="">
                        <label class="text-secondary h5">Estado dos Instrumentos</label>
                    </div>
                    <div style="max-height: 400px;">
                        <canvas class="mx-auto" id="model07" style="min-height: 200px;"></canvas>
                    </div>
                </div> 
            </div>
        </div>     
    </div>
</div>
<br>







{% endblock  %}

app/templates/layout_login.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link rel="stylesheet" href="../static/main.css" />
  </head>
  <body>
    <div class="main">
      <div class="bg-image background-login" style="background-image: url('https://c.pxhere.com/photos/79/26/music_violin_person_string_instrument-138718.jpg!d');height: 100vh;">
        <aside class="wrapper-aside float-right d-flex flex-column h-100 pt-5 pr-5 pl-5 pb-3" style="
        background-color: white;
          ">
          <div class="mb-auto mt-5 pt-5">
            <div class="container">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class='text-center alert alert-{{ category }}'>
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}  
              {% endwith %}
            </div>

            {% block access %}
            {% endblock  %}

            
          </div>
          <div class="container text-center" style="max-width: 300px;">
            <span class="text-muted">Desenvolvido por alunos do curso de S.I. da PUC Minas Virtual.</span>
          </div>
        </aside>
      </div>
    </div>


     <!--Modal para recuperacao de senha-->
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-rec-senha1">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content"> 
          <div class="modal-header text-center text-info"> 
            <h4>Recuperar Senha</h4>
            <button type="button" class="close" data-dismiss="modal">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>       
            <form class="border p-5  shadow bg-white rounded" action="#" method="POST" autocomplete="off"> 
              <div class="mb-3 text-center">
                  <p>Digite seu endereço de e-mail. Você receberá um link por e-mail para
                      criar uma nova senha.</p>
              </div>
              <div class="form-group">
                  <label for="name">Email</label>
                  <input type="email" class="form-control" id="name" placeholder="Email" value=""
                      required />
              </div>
              <div class="text-center mt-3">
                  <button class="btn btn-primary" type="submit">Enviar</button>
              </div>
          </form>
      </div>
    </div>
  </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/login.html
{% extends "layout_login.html" %}

    {% block access %}

    <form class="p-4 bg-white border-bottom" action="" method="POST" style=" 
              opacity: 0.9;">
      {{ form.hidden_tag() }}
      <div class="mb-5 text-center">
        <h3 class="text-info">Orquestra Criarte Digital</h3>
      </div>
      <div class="form-group">
        <label for="inputEmail">Email</label>
        {% if form.email.errors %}
          {{ form.email(class = 'form-control is-invalid') }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class = 'form-control', placeholder = 'email') }}
        {% endif %}
      </div>
      <div class="form-group mb-2 text-dark">
        <label for="inputPassword">Senha</label>
        {% if form.password.errors %}
          {{ form.password(class = 'form-control is-invalid') }}
          <div class="invalid-feedback">
            {% for error in errors %}
              <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.password(class = 'form-control', placeholder = 'senha') }}
        {% endif %}
      </div>
      <div class="form-group d-flex">
        <div class="mx-auto">
          {{ form.remember(class = 'form-check-input') }}
          <label class="form-check-label" for="exampleCheck1">Lembrar senha</label>
        </div>
      </div>
      <div class="text-center mt-3">{{ form.submit(class = 'btn btn-primary text-white') }}</div>
      <div class="d-flex mt-3">
        <div class="form-group">
          <small class=""><a class="form-text text-secondary text-muted text-right" href="{{ url_for('user.request_password')}}">Esqueci a senha</a></small>
        </div>
        <div class="form-group ml-auto">
          <small class=""><a class="form-text text-secondary text-muted text-right" href="{{ url_for('user.register') }}">Criar uma conta</a></small>
        </div>
      </div>
    </form>

    {% endblock  %}